<?php
/*
Plugin Name: wp_title_tooltips
Plugin URI: http://www.ll19.com/?p=115
Description: Add title tooltips in your wordpress. Upload `wp_title_tooltips` to the `/wp-content/plugins/` directory. Change <code>&lt;?php the_title(); ?></code> to <code>&lt;?php wpttt_the_title(); ?></code>. Place <code>&lt;?php glll_wpttt(); ?></code> in your templates~ For example <code>&lt;h3>&lt;a href="&lt;?php the_permalink() ?>">&lt;?php wpttt_the_title(); ?>&lt;/a>&lt;/h3>&lt;?php glll_wpttt(); ?></code>.
Version: 1.2.4
Author: LL19.com
Author URI: http://www.ll19.com/
*/

/*
add js&&css
*/
add_action('wp_head', 'wpttt_css_js');
function wpttt_css_js() {
	echo "\n" . '<!-- Start Of Script Generated By wp_title_tooltips 1.2.2 -->' . "\n";
	if (@ file_exists(TEMPLATEPATH . '/glll_wttt.php')) {
		echo '<link rel="stylesheet" href="' . get_stylesheet_directory_uri() . '/style.css" type="text/css" media="screen" />' . "\n";
		wp_print_scripts('jquery');
		echo '<script src="' . get_stylesheet_directory_uri() . '/jquery.wptooltips.js" type="text/javascript"></script>' . "\n";
	} else {
		echo '<link rel="stylesheet" href="' . WP_PLUGIN_URL . '/wp_title_tooltips/style.css" type="text/css" media="screen" />' . "\n";
		wp_print_scripts('jquery');
		echo '<script src="' . WP_PLUGIN_URL . '/wp_title_tooltips/jquery.wptooltips.js" type="text/javascript"></script>' . "\n";
	}
	echo '<!-- End Of Script Generated By wp_title_tooltips 1.2.2  -->' . "\n";
}
add_action('wp_footer', 'wp_i_tooltips');
function wp_i_tooltips() {
	echo "<div class=\"wp_i_tooltips\"></div>";
}
function wpttt_the_title() {
	$wpttt_content = "<span id=\"wttt-this-" . get_the_ID() . "\">" . get_the_title() . "</span>";
	echo $wpttt_content;
}
function glll_wpttt() {
?>
	 <div id="wttt-this-show-<?php the_ID(); ?>" style="display:none">
	 <div class="wttt-title">
	 <a href="javascript:void(0);" onclick="wtttCallCommentList(<?php the_ID(); ?>,'<?php echo get_the_author_email(); ?>','<?php echo get_settings('siteurl'); ?>')"><IMG alt="" src="<?php echo get_settings('siteurl'); ?>/wp-content/plugins/wp_title_tooltips/notes.png"></a>
	 <div id="wttt-<?php the_ID(); ?>-content"  class="wttt-content">
	 <h4><?php the_title(); ?></h4>
	 <div class="tooltips_entry"><span>&para;&nbsp;Posted <?php unset($previousday); printf(__('%1$s'), the_date('d F Y', false)) ?></span><span>&sect;&nbsp;<?php the_category(' &sect; ') ?></span><span>&Dagger;&nbsp;<?php comments_popup_link(__('Comments (0)'), __('Comments (1)'), __('Comments (%)')) ?></span><span>&plusmn;&nbsp;<?php the_tags('Tags: ', '+ ', '&nbsp;'); ?></span>
	 </div>
	 </div>
	 </div>
	 </div>
	 <script type="text/javascript">
	 jQuery(document).ready(function(){
	 try{
	 jQuery("#wttt-this-<?php the_ID(); ?>").wptooltips(".wp_i_tooltips","#wttt-this-show-<?php the_ID(); ?>","<?php if (@ file_exists(TEMPLATEPATH . '/jquery.wptooltips.js')) {echo get_stylesheet_directory_uri(). "/";} else {echo WP_PLUGIN_URL. "/wp_title_tooltips/";}?>");
	 } catch (e){
	 jQuery(".wp_i_tooltips").append("(wp_title_tooltips error.)");
	 }
	 })
	 </script>
<?php } ?>